language:
 - python

python:
 - "3.6"

cache:
 - pip

before_install:
 - pip install pytest pytest-cov
 - pip install coveralls

install: 
 - pip install .

script:
 - pytest tests

after_success:
 - coveralls

notifications:
 email: false
