language: python

cache: pip

python:
 - "3.6"

before_install:
 - pip install pytest pytest-cov
 - pip install coveralls

install: 
 - pip install .

script:
 - pytest tests

after_success:
 - coveralls

notifications:
 email: false
