language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

before_install:
 # create display with large resolution
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
 - python setup_wonambi.py --get_files

install: 
 # install requirements
 - pip install numpy scipy pyqt5 
 - pip install pytest pytest-qt pytest-cov codecov 
 - pip install sphinx sphinx_rtd_theme
 - pip install nibabel mne
 - pip install https://github.com/vispy/vispy/archive/master.zip

 - pip install -e .

before_script:
  - "export DISPLAY=:99.0"

script:
 - python -c "import vispy; print(vispy.sys_info()); exit()"
 - python setup_wonambi.py --tests
 - pip uninstall -y nibabel mne
 - python setup_wonambi.py --test_import
 - python setup_wonambi.py --docs

after_success:
 - codecov

notifications:
 email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : master
   local_dir : $HTML_PATH
   repo : wonambi-python/wonambi-python.github.io
   github_token : $GITHUB_TOKEN
 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASSWORD
   on:
     tags: true
